(()=>{'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),scoreEl=document.getElementById('score');
const W=1100,H=700,CX=550,CY=405,RX=430,RY=235,CEILING=460,TEAM={BLUE:0,RED:1};
const keys=new Set(),pressed=new Set(),input={x:0,y:0,a:false,b:false,c:false,aTap:false,bTap:false,cTap:false};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,norm=(x,y)=>{const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d}},rnd=(a,b)=>a+Math.random()*(b-a),d2=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
let last=performance.now(),score=[0,0],shake=0,flash=0,banner='DOME AIRBALL',resetTimer=0;
const classData={ninja:{name:'NINJA',speed:245,jump:690,air:.95},staff:{name:'STAFF',speed:215,jump:650,air:.78},gauntlet:{name:'GAUNTLET',speed:205,jump:665,air:.83}};
const players=[];
function add(team,cls,x,y,human=false){const p={id:players.length,team,cls,x,y,z:0,vx:0,vy:0,vz:0,face:team? -1:1,human,onGround:true,wallJump:true,attackCd:0,tossCd:0,jumpCd:0,airTime:0,stun:0,anim:0,hasBall:false};players.push(p);return p}
const human=add(0,'ninja',350,405,true);add(0,'staff',390,300);add(0,'gauntlet',390,510);add(1,'ninja',750,405);add(1,'staff',710,300);add(1,'gauntlet',710,510);
const ball={x:CX,y:CY,z:0,vx:0,vy:0,vz:0,owner:null,lastToss:null,lastTouch:null,volleyTeam:null,volleyBy:null,volleyTime:0,trails:[],idle:0,airTime:0};
const projectiles=[],effects=[],ripples=[];
// Four cross-position rings. Blue defends west+north; Red defends east+south.
const rings=[{team:0,x:CX-RX*.82,y:CY,z:190,axis:'v'},{team:1,x:CX+RX*.82,y:CY,z:190,axis:'v'},{team:0,x:CX,y:CY-RY*.80,z:190,axis:'h'},{team:1,x:CX,y:CY+RY*.80,z:190,axis:'h'}];
function reset(goal=false){const pos=[[350,405],[390,300],[390,510],[750,405],[710,300],[710,510]];players.forEach((p,i)=>Object.assign(p,{x:pos[i][0],y:pos[i][1],z:0,vx:0,vy:0,vz:0,stun:0,hasBall:false,onGround:true,wallJump:true,jumpCd:0,airTime:0}));Object.assign(ball,{x:CX,y:CY,z:0,vx:0,vy:0,vz:0,owner:null,lastToss:null,lastTouch:null,volleyTeam:null,volleyBy:null,volleyTime:0,trails:[],idle:0,airTime:0});projectiles.length=0;if(goal)flash=1}
function ellipseValue(x,y){return ((x-CX)/RX)**2+((y-CY)/RY)**2}
function confine(o,bounce=.35){let nx=(o.x-CX)/RX,ny=(o.y-CY)/RY,q=nx*nx+ny*ny;if(q<=1)return false;const s=1/Math.sqrt(q);o.x=CX+nx*s*RX;o.y=CY+ny*s*RY;const gx=(o.x-CX)/(RX*RX),gy=(o.y-CY)/(RY*RY),n=norm(gx,gy),dot=o.vx*n.x+o.vy*n.y;if(dot>0){o.vx-=n.x*dot*(1+bounce);o.vy-=n.y*dot*(1+bounce)}return true}
function possess(p){players.forEach(q=>q.hasBall=false);p.hasBall=true;ball.owner=p;ball.lastTouch=p;ball.vx=ball.vy=ball.vz=0;ball.z=0}
function release(){if(ball.owner)ball.owner.hasBall=false;ball.owner=null}
function toss(p){if(!p.hasBall||p.tossCd>0||p.stun>0)return;release();ball.lastToss=p;ball.lastTouch=p;ball.volleyTeam=null;ball.volleyBy=null;ball.x=p.x+p.face*24;ball.y=p.y;ball.z=24;ball.vx=p.face*95+p.vx*.25;ball.vy=p.vy*.2;ball.vz=430;p.tossCd=.65;effects.push({type:'text',x:p.x,y:p.y,z:70,t:.65,text:'TOSS'});}
function wallNormal(p){const ex=(p.x-CX)/RX,ey=(p.y-CY)/RY;return norm(-ex/RX,-ey/RY)}
function jump(p){if(p.stun>0||p.jumpCd>0)return;if(p.onGround){p.vz=classData[p.cls].jump;p.onGround=false;p.jumpCd=.18;p.airTime=0;p.wallJump=true;effects.push({type:'dust',x:p.x,y:p.y,z:0,t:.35})}else if(ellipseValue(p.x,p.y)>.88&&p.wallJump){const n=wallNormal(p);const power=p.cls==='ninja'?340:285;p.vx+=n.x*power;p.vy+=n.y*power;p.vz=p.cls==='ninja'?680:610;p.wallJump=false;p.jumpCd=.22;p.airTime=0;ripples.push({x:p.x,y:p.y,z:p.z,t:.5})}else tryVolley(p)}
function tryVolley(p){if(ball.owner||p.z<60||d2(p,ball)>78||Math.abs((p.z+25)-ball.z)>95)return false;if(ball.lastToss===p){effects.push({type:'text',x:p.x,y:p.y,z:p.z+55,t:.7,text:'SELF TOSS ×'});return false}const targets=rings.filter(r=>r.team!==p.team).sort((a,b)=>d2(a,p)-d2(b,p));const r=targets[0],dir=norm(r.x-p.x,r.y-p.y),time=clamp(d2(p,r)/430,.5,1.05);release();ball.x=p.x+dir.x*28;ball.y=p.y+dir.y*28;ball.z=p.z+28;ball.vx=(r.x-ball.x)/time;ball.vy=(r.y-ball.y)/time;ball.vz=(r.z-ball.z)/time+190*time;ball.volleyTeam=p.team;ball.volleyBy=p;ball.volleyTime=1.45;ball.lastTouch=p;p.vz+=55;shake=.16;effects.push({type:'burst',x:ball.x,y:ball.y,z:ball.z,t:.45});return true}
function attack(p){if(p.attackCd>0||p.stun>0)return;p.attackCd=p.cls==='ninja'?.85:.62;p.anim=.3;if(p.cls==='ninja'){const aim=norm(p.face,0);projectiles.push({x:p.x+aim.x*24,y:p.y,z:p.z+42,vx:aim.x*560,vy:aim.y*560,t:1.15,team:p.team,owner:p,rot:0})}else{const range=p.cls==='staff'?92:68;for(const q of players){if(q.team===p.team||d2(p,q)>range||Math.abs(q.z-p.z)>(p.cls==='staff'?48:90))continue;const n=norm(q.x-p.x,q.y-p.y);q.vx+=n.x*(p.cls==='staff'?150:215);q.vy+=n.y*(p.cls==='staff'?150:215);q.vz+=p.cls==='gauntlet'?120:25;q.stun=p.cls==='staff'?.38:.3;drop(q);effects.push({type:'hit',x:q.x,y:q.y,z:q.z+30,t:.3})}}}
function drop(p){if(!p.hasBall)return;release();ball.x=p.x;ball.y=p.y;ball.z=p.z+30;ball.vx=p.vx*.45;ball.vy=p.vy*.45;ball.vz=125}
function ai(p,dt){if(p.stun>0)return{x:0,y:0,a:false,b:false,c:false};let tx=ball.owner?ball.owner.x:ball.x,ty=ball.owner?ball.owner.y:ball.y,a=false,b=false,c=false;if(p.hasBall){tx=CX+(p.team? -95:95);ty=CY+(p.id%2? -70:70);if(Math.random()<dt*2.4)b=true}else if(!ball.owner&&ball.z>50){tx=ball.x;ty=ball.y;if(d2(p,ball)<135&&Math.abs(p.z+30-ball.z)<120)c=true}else if(p.cls==='gauntlet'){const own=rings.filter(r=>r.team===p.team),r=own[p.id%2];tx=lerp(CX,r.x,.72);ty=lerp(CY,r.y,.72);if(players.some(q=>q.team!==p.team&&d2(p,q)<75))a=true}else{tx=ball.owner?ball.owner.x:ball.x;ty=ball.owner?ball.owner.y:ball.y;if(d2(p,{x:tx,y:ty})<(p.cls==='staff'?95:150))a=Math.random()<.08;if(p.cls==='ninja'&&ball.z>40&&d2(p,ball)<180)c=true}const n=norm(tx-p.x,ty-p.y);return{x:n.x,y:n.y,a,b,c}}
function readInput(){let x=input.x,y=input.y;if(keys.has('a')||keys.has('arrowleft'))x--;if(keys.has('d')||keys.has('arrowright'))x++;if(keys.has('w')||keys.has('arrowup'))y--;if(keys.has('s')||keys.has('arrowdown'))y++;const m=Math.hypot(x,y);if(m>1){x/=m;y/=m}const o={x,y,a:input.aTap||pressed.has('j'),b:input.bTap||pressed.has('k'),c:input.cTap||pressed.has('l')};pressed.clear();input.aTap=input.bTap=input.cTap=false;return o}
function updatePlayer(p,dt){p.attackCd=Math.max(0,p.attackCd-dt);p.tossCd=Math.max(0,p.tossCd-dt);p.jumpCd=Math.max(0,p.jumpCd-dt);p.stun=Math.max(0,p.stun-dt);p.anim=Math.max(0,p.anim-dt);let c=p.human?readInput():ai(p,dt);if(p.stun>0)c={x:0,y:0,a:false,b:false,c:false};const cd=classData[p.cls],air=p.onGround?1:cd.air,acc=p.onGround?11:5.5;p.vx=lerp(p.vx,c.x*cd.speed*air,clamp(acc*dt,0,1));p.vy=lerp(p.vy,c.y*cd.speed*air,clamp(acc*dt,0,1));if(Math.abs(c.x)>.12)p.face=Math.sign(c.x);p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;if(!p.onGround){p.airTime+=dt;const gravity=p.vz>0?1040:880;p.vz-=gravity*dt;if(p.airTime>2.35)p.vz=Math.min(p.vz,-520);}p.vz=clamp(p.vz,-760,760);if(p.z<=0){p.z=0;p.vz=0;p.onGround=true;p.wallJump=true;p.airTime=0}else p.onGround=false;if(p.z>CEILING-35){p.z=CEILING-35;p.vz=-Math.abs(p.vz)*.28;ripples.push({x:p.x,y:p.y,z:CEILING,t:.45})}confine(p,.15);if(c.a)attack(p);if(c.b)toss(p);if(c.c)jump(p);if(p.hasBall){ball.x=p.x+p.face*22;ball.y=p.y+8;ball.z=10}}
function updateBall(dt){if(ball.owner){ball.airTime=0;return;}ball.volleyTime=Math.max(0,ball.volleyTime-dt);ball.trails.push({x:ball.x,y:ball.y,z:ball.z,t:.34});if(ball.trails.length>24)ball.trails.shift();ball.trails.forEach(t=>t.t-=dt);ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;ball.z+=ball.vz*dt;ball.airTime+=dt;const ballGravity=ball.vz>0?610:520;ball.vz-=ballGravity*dt;if(ball.airTime>4.2)ball.vz=Math.min(ball.vz,-420);ball.vz=clamp(ball.vz,-680,680);ball.vx*=Math.pow(.996,dt*60);ball.vy*=Math.pow(.996,dt*60);if(ball.z<0){ball.z=0;ball.airTime=0;ball.vz=Math.abs(ball.vz)*.38;ball.vx*=.94;ball.vy*=.94;if(Math.abs(ball.vz)<30)ball.vz=0}if(ball.z>CEILING){ball.z=CEILING;ball.vz=-Math.max(180,Math.abs(ball.vz)*.58);ripples.push({x:ball.x,y:ball.y,z:CEILING,t:.65})}if(confine(ball,.72))ripples.push({x:ball.x,y:ball.y,z:ball.z,t:.5});if(!Number.isFinite(ball.x+ball.y+ball.z)||Math.abs(ball.x)>5000||Math.abs(ball.y)>5000||ball.z>1500){Object.assign(ball,{x:CX,y:CY,z:80,vx:0,vy:0,vz:0,owner:null,lastToss:null,volleyTeam:null,volleyTime:0})}for(const p of players){if(p.stun<=0&&ball.z<34&&d2(p,ball)<34&&Math.hypot(ball.vx,ball.vy)<300){possess(p);break}}checkGoal()}
function checkGoal(){if(ball.volleyTime<=0||ball.volleyTeam==null)return;for(const r of rings){if(r.team===ball.volleyTeam)continue;const horiz=d2(ball,r),dz=Math.abs(ball.z-r.z);if(horiz<34&&dz<32){score[ball.volleyTeam]++;scoreEl.textContent=`BLUE ${score[0]} — ${score[1]} RED`;banner='GOAL!';flash=1;shake=.42;ball.volleyTime=0;resetTimer=.75;return}}}
function updateProjectiles(dt){for(let i=projectiles.length-1;i>=0;i--){const k=projectiles[i];k.x+=k.vx*dt;k.y+=k.vy*dt;k.rot+=dt*18;k.t-=dt;let hit=false;if(confine(k,.05))hit=true;for(const p of players){if(p.team===k.team||d2(p,k)>30||Math.abs(p.z+35-k.z)>65)continue;p.stun=.28;p.vx+=Math.sign(k.vx)*95;drop(p);effects.push({type:'hit',x:p.x,y:p.y,z:p.z+35,t:.3});hit=true;break}if(hit||k.t<=0)projectiles.splice(i,1)}}
function update(dt){if(keys.has('r'))reset();players.forEach(p=>updatePlayer(p,dt));updateBall(dt);updateProjectiles(dt);effects.forEach(e=>e.t-=dt);ripples.forEach(e=>e.t-=dt);for(let i=effects.length-1;i>=0;i--)if(effects[i].t<=0)effects.splice(i,1);for(let i=ripples.length-1;i>=0;i--)if(ripples[i].t<=0)ripples.splice(i,1);flash=Math.max(0,flash-dt*1.4);shake=Math.max(0,shake-dt);if(resetTimer>0&&(resetTimer-=dt)<=0)reset(true)}
function project(x,y,z=0){return{x,y:y-z*.58}}
function shadow(x,y,z,r=24){ctx.save();ctx.globalAlpha=clamp(.42-z/850,.09,.42);ctx.fillStyle='#02050a';ctx.beginPath();ctx.ellipse(x,y+13,r*(1-z/950),r*.34*(1-z/950),0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawArena(){const bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#14283a');bg.addColorStop(.58,'#091624');bg.addColorStop(1,'#03080e');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);ctx.fillStyle='#0d2330';ctx.beginPath();ctx.ellipse(CX,CY,RX+28,RY+28,0,0,Math.PI*2);ctx.fill();const floor=ctx.createRadialGradient(CX,CY-30,30,CX,CY,470);floor.addColorStop(0,'#315668');floor.addColorStop(.7,'#193746');floor.addColorStop(1,'#0d2431');ctx.fillStyle=floor;ctx.beginPath();ctx.ellipse(CX,CY,RX,RY,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#a4e8ff66';ctx.lineWidth=5;ctx.stroke();ctx.strokeStyle='#d8f7ff2d';ctx.lineWidth=2;for(let r=.25;r<1;r+=.25){ctx.beginPath();ctx.ellipse(CX,CY,RX*r,RY*r,0,0,Math.PI*2);ctx.stroke()}ctx.beginPath();ctx.moveTo(CX-RX,CY);ctx.lineTo(CX+RX,CY);ctx.moveTo(CX,CY-RY);ctx.lineTo(CX,CY+RY);ctx.stroke();
// Tall transparent dome ribs
ctx.save();ctx.strokeStyle='#9de9ff2d';ctx.lineWidth=3;ctx.setLineDash([8,10]);ctx.beginPath();ctx.ellipse(CX,CY-118,RX+10,RY+160,0,Math.PI,Math.PI*2);ctx.stroke();ctx.setLineDash([]);for(const x of [-.7,-.35,0,.35,.7]){ctx.beginPath();ctx.moveTo(CX+x*RX,CY+Math.sqrt(1-x*x)*RY);ctx.quadraticCurveTo(CX+x*RX*.52,CY-400,CX+x*RX,CY-Math.sqrt(1-x*x)*RY);ctx.stroke()}ctx.restore();rings.forEach(drawRing);ripples.forEach(drawRipple)}
function drawRipple(e){const p=project(e.x,e.y,e.z),a=clamp(e.t*2,0,1),rad=(1-e.t)*70+14;ctx.save();ctx.globalAlpha=a;ctx.strokeStyle='#b9f4ff';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(p.x,p.y,rad,rad*.45,0,0,Math.PI*2);ctx.stroke();ctx.restore()}
function drawRing(r){shadow(r.x,r.y,r.z,32);const p=project(r.x,r.y,r.z);ctx.save();ctx.translate(p.x,p.y);ctx.strokeStyle=r.team===0?'#45c8ff':'#ff5873';ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=24;ctx.lineWidth=10;ctx.beginPath();ctx.ellipse(0,0,r.axis==='h'?36:18,r.axis==='h'?18:36,0,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#f0fbffcc';ctx.lineWidth=2;ctx.stroke();ctx.restore();ctx.strokeStyle='#c9f5ff25';ctx.beginPath();ctx.moveTo(r.x,r.y);ctx.lineTo(p.x,p.y);ctx.stroke()}
function drawPlayer(p){const q=project(p.x,p.y,p.z),team=p.team===0?'#2e9eea':'#db4059',trim=p.team===0?'#bcecff':'#ffd2d9';shadow(p.x,p.y,p.z,27);ctx.save();ctx.translate(q.x,q.y);ctx.globalAlpha=p.stun>0?.65:1;const run=Math.sin(performance.now()/90+p.id)*Math.min(5,Math.hypot(p.vx,p.vy)/60),kick=p.anim>0?1:0;
// illustrated body silhouette
ctx.strokeStyle='#07111c';ctx.lineWidth=4;ctx.fillStyle=team;ctx.beginPath();ctx.roundRect(-17,-31,34,48,12);ctx.fill();ctx.stroke();ctx.fillStyle=trim;ctx.beginPath();ctx.arc(0,-42,16,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#172531';ctx.beginPath();ctx.arc(0,-42,13,Math.PI,Math.PI*2);ctx.fill();if(p.cls==='ninja'){ctx.fillStyle=team;ctx.fillRect(-16,-47,32,10);ctx.fillStyle='#fff';ctx.fillRect(-7,-44,4,2);ctx.fillRect(3,-44,4,2)}else{ctx.fillStyle='#d6b77e';ctx.beginPath();ctx.arc(0,-43,13,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle='#402d20';ctx.fillRect(-7,-42,4,2);ctx.fillRect(3,-42,4,2)}
ctx.strokeStyle=trim;ctx.lineWidth=7;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-9,-5);ctx.lineTo(-15,20+run);ctx.moveTo(9,-5);ctx.lineTo(15,20-run);ctx.moveTo(-13,-18);ctx.lineTo(-24,-2);ctx.moveTo(13,-18);ctx.lineTo((24+kick*10)*p.face,-4);ctx.stroke();
if(p.cls==='ninja'){ctx.strokeStyle='#e9f5ff';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(16*p.face,-13);ctx.lineTo(31*p.face,-22);ctx.stroke();ctx.fillStyle='#e9f5ff';ctx.beginPath();ctx.moveTo(31*p.face,-22);ctx.lineTo(21*p.face,-23);ctx.lineTo(26*p.face,-15);ctx.fill()}else if(p.cls==='staff'){ctx.strokeStyle='#d7ae58';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(-31*p.face,7);ctx.lineTo(34*p.face,-14);ctx.stroke()}else{ctx.fillStyle='#f1a46e';ctx.strokeStyle='#07111c';ctx.lineWidth=3;ctx.beginPath();ctx.arc(26*p.face,-5,11,0,Math.PI*2);ctx.fill();ctx.stroke()}
ctx.fillStyle='#f6fbff';ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.fillText(classData[p.cls].name,0,-65);if(p.stun>0){ctx.fillStyle='#ffe55d';ctx.font='20px sans-serif';ctx.fillText('✦  ✦',0,-80)}ctx.restore()}
function drawBall(){if(ball.owner)return;for(const t of ball.trails){if(t.t<=0)continue;const p=project(t.x,t.y,t.z);ctx.save();ctx.globalAlpha=t.t*.45;ctx.fillStyle='#d6f5ff';ctx.beginPath();ctx.arc(p.x,p.y,5+t.z*.012,0,Math.PI*2);ctx.fill();ctx.restore()}shadow(ball.x,ball.y,ball.z,22);ctx.save();ctx.strokeStyle='#ffe57688';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(ball.x,ball.y+12,26,9,0,0,Math.PI*2);ctx.stroke();ctx.restore();const p=project(ball.x,ball.y,ball.z),s=15+ball.z*.025;ctx.save();ctx.translate(p.x,p.y);ctx.shadowColor='#c6f5ff';ctx.shadowBlur=22;ctx.fillStyle='#f3fbff';ctx.strokeStyle='#102638';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,s,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#56badb';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,s*.57,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(-s*.7,0);ctx.lineTo(s*.7,0);ctx.stroke();ctx.restore();if(ball.lastToss){ctx.fillStyle='#f5fbff';ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.fillText(`TOSS: ${ball.lastToss.team===0?'BLUE':'RED'} ${classData[ball.lastToss.cls].name}`,p.x,p.y-s-12)}}
function drawProjectiles(){for(const k of projectiles){const p=project(k.x,k.y,k.z);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(k.rot);ctx.strokeStyle='#fff';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-13,0);ctx.lineTo(13,0);ctx.moveTo(0,-7);ctx.lineTo(0,7);ctx.stroke();ctx.restore()}}
function drawEffects(){for(const e of effects){const p=project(e.x,e.y,e.z),a=clamp(e.t*3,0,1);ctx.save();ctx.globalAlpha=a;if(e.type==='text'){ctx.fillStyle='#fff5a6';ctx.font='900 18px system-ui';ctx.textAlign='center';ctx.fillText(e.text,p.x,p.y)}else{ctx.strokeStyle=e.type==='hit'?'#ffdd8a':'#c9f7ff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(p.x,p.y,12+(1-e.t)*46,0,Math.PI*2);ctx.stroke()}ctx.restore()}}
function draw(){ctx.save();if(shake>0)ctx.translate(rnd(-5,5)*shake/.42,rnd(-4,4)*shake/.42);drawArena();[...players].sort((a,b)=>(a.y-a.z*.18)-(b.y-b.z*.18)).forEach(drawPlayer);drawProjectiles();drawBall();drawEffects();ctx.restore();ctx.fillStyle='#e8f7ff';ctx.font='13px system-ui';ctx.textAlign='left';ctx.fillText('A 武器　B トス　C ジャンプ / 空中ボレー',34,30);ctx.textAlign='right';ctx.fillText('自分のトスは得点不可・敵のトスは奪取OK',W-34,30);if(flash>0){ctx.fillStyle=`rgba(255,255,255,${flash*.28})`;ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.font='900 54px system-ui';ctx.textAlign='center';ctx.fillText(banner,CX,100)}}
function loop(t){const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(!keys.has(k))pressed.add(k);keys.add(k);if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(e.key.toLowerCase()))e.preventDefault()});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function bind(id,p){const el=document.getElementById(id),down=e=>{e.preventDefault();input[p]=true;input[p+'Tap']=true;el.classList.add('pressed')},up=e=>{e.preventDefault();input[p]=false;el.classList.remove('pressed')};el.addEventListener('pointerdown',down);['pointerup','pointercancel','pointerleave'].forEach(n=>el.addEventListener(n,up))}bind('btnA','a');bind('btnB','b');bind('btnC','c');
const stick=document.getElementById('stick');
const knob=document.getElementById('knob');
let sid=null;
function sm(e){
  const r=stick.getBoundingClientRect();
  const cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.34;
  let dx=e.clientX-cx,dy=e.clientY-cy;
  const d=Math.hypot(dx,dy);
  if(d>max){dx*=max/d;dy*=max/d;}
  input.x=dx/max;input.y=dy/max;
  knob.style.transform=`translate(${dx}px,${dy}px)`;
}
stick.addEventListener('pointerdown',e=>{sid=e.pointerId;stick.setPointerCapture(sid);sm(e);});
stick.addEventListener('pointermove',e=>{if(e.pointerId===sid)sm(e);});
function se(e){
  if(e.pointerId!==sid)return;
  sid=null;input.x=input.y=0;
  knob.style.transform='translate(0,0)';
}
stick.addEventListener('pointerup',se);
stick.addEventListener('pointercancel',se);
reset();requestAnimationFrame(loop);
})();
